eureka:
  instance:
    hostname: localhost
  server:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka
spring:
  cloud:
    config:
      overrideSystemProperties: false