spring:
  data:
    mongodb:
      username: hajuna
      password: hajuna
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090