spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: hajuna
    password: hajuna
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.hajuna.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments

server:
  port: 8070