spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service
api:
  prefix: /api/v1
logging:
  level:
    org:
      springframework:
        beans:
          factory:
            support=DEBUG:
